#!/bin/sh
echo digraph statemach {
sed '/ => {$/{:a;/^\([ \t]*\).*=> {.*\n\1}/!{N;ba};s/\n[\t ]*/ /g}' | sed -n "s/self.reset()/Start/;s/\\\\/\\\\\\\\/g;s/^\s*(\([^,]*\), b'\(.[^']*\)') => \(\([^,{]*\)\|\({\)[^};]*; \([^}]*\) }\)\(\|,\)$/\t\1 -> \4\6 [label=\"'\2'\"]\5;/p" | sed "s/{;/ [color=\"red\"];/"
echo }
